# Generated by Django 3.1.3 on 2020-12-18 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Кошка', 'CAT'), ('Собака', 'DOF'), ('Попугай', 'Попугай')], max_length=30, verbose_name='Тип животного')),
                ('klass', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Порода')),
                ('size', models.CharField(choices=[('Большого телосложения', 'Большого телосложения'), ('Среднего телосложения', 'Среднего телосложения'), ('Маленького телосложения', 'Маленького телосложения')], max_length=100, verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Окрас')),
                ('life', models.SmallIntegerField(verbose_name='Средняя продолжительность жизни')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal', verbose_name='Тип животного')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80, verbose_name='Кличка питомца')),
                ('sex', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол питомца')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_enter', models.DateField(default=datetime.date(2020, 12, 18), verbose_name='Дата поступления')),
                ('year', models.SmallIntegerField(verbose_name='Возраст питомца')),
                ('photo', models.ImageField(blank=True, upload_to='pet_images/%Y/%m/%d', verbose_name='Фото питомца')),
                ('like', models.SmallIntegerField(default=0, verbose_name='Лайки')),
                ('vetpasport', models.BooleanField(default=False, verbose_name='Наличие ветпаспорта у питомца')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.breed', verbose_name='Порода питомца')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.animal', verbose_name='Тип питомца')),
            ],
        ),
    ]
