# Generated by Django 3.1.3 on 2020-12-18 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201218_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_enter',
            field=models.DateField(default=datetime.date(2020, 12, 19), verbose_name='Дата поступления'),
        ),
    ]
