# Generated by Django 3.1.3 on 2020-12-19 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20201219_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='klass',
        ),
        migrations.AddField(
            model_name='animal',
            name='icon',
            field=models.ImageField(blank=True, upload_to='animal_icons/%Y/%m/%d', verbose_name='Иконка животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Кошка', 'Кошка'), ('Собака', 'Собака'), ('Попугай', 'Попугай')], max_length=30, verbose_name='Тип животного'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogpost',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='small_decc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Короткий текст сообщения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_enter',
            field=models.DateField(default=datetime.date(2020, 12, 20), verbose_name='Дата поступления'),
        ),
    ]
