# Generated by Django 3.1.3 on 2020-12-28 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20201228_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_enter',
            field=models.DateField(default=datetime.date(2020, 12, 29), verbose_name='Дата поступления'),
        ),
    ]
